server:
  port: 8080
spring:
  application:
    name: "mq-reactive"
commons:
  jms:
    output-concurrency: 2
    output-queue: "DEV.QUEUE.1"
    producer-ttl: 60
    input-concurrency: 2
    input-queue: "DEV.QUEUE.1"
ibm:
  mq:
    channel: "DEV.APP.SVRCONN"
    user: "app"
    queue-manager: QM1
