server:
  port: 8081
logging:
  level:
    root: INFO
spring:
  application:
    name: "mq-reactive-replier"
commons:
  jms:
    output-concurrency: 5
    output-queue: "DEV.QUEUE.2"
    producer-ttl: 60
    reactive: true
    input-concurrency: 5
    input-queue: "DEV.QUEUE.1"
ibm:
  mq:
    channel: "DEV.APP.SVRCONN"
    user: "app"
    password: passw0rd
    queue-manager: QM1
