server:
  port: 8080
spring:
  application:
    name: "mq-reactive"
logging:
  level:
    root: INFO
commons:
  jms:
    output-concurrency: 5
    output-queue: "DEV.QUEUE.1"
    producer-ttl: 60
    reactive: true
    input-concurrency: 5
    input-queue: "DEV.QUEUE.2"
    input-queue-set-queue-manager: true # enable it to set queue manager using a temporary queue
    selector-mode: CONTEXT_SHARED # CONTEXT_SHARED | CONTEXT_PER_MESSAGE
ibm:
  mq:
    channel: "DEV.APP.SVRCONN"
    user: "app"
    password: passw0rd
    queue-manager: QM1
management:
  endpoint:
    health:
      show-details: always
