server:
  port: 8080
spring:
  application:
    name: "mq-reactive"
logging:
  level:
    root: INFO
commons:
  jms:
    output-concurrency: 1
    reactive: true
    input-concurrency: 1
ibm:
  mq:
    channel: "DEV.APP.SVRCONN"
    user: "app"
    password: passw0rd
    queue-manager: QM1
management:
  health:
    probes:
      enabled: true # To test liveness and readiness probes
    jms:
      enabled: false
  endpoint:
    health:
      show-details: always
my:
  selector-mode: MULTI_CONTEXT_SHARED