graph TD
  X[ConnectionFactory] -->|create| A
  A[Connection] -->|create| B(Session)
  B --> |create| C(TemporaryQueue)
  A -->|create| D(Session)
  D -->|create| E(MessageConsumer: TemporaryQueue)
  E -->|notifies|F[MessageListener]
  A -->|create| G(Session)
  G -->|create| H(MessageConsumer: TemporaryQueue)
  H -->|notifies|F
  A -->|create| I(Session)
  I -->|create| J(MessageConsumer: TemporaryQueue)
  J -->|notifies|F
